[package]
name = "rustledge"
version = "0.0.4"
authors = ["Sahandevs <sahandevs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.6"
rocket_contrib = "0.4.6"
git_collector = { path = "../git_collector" }
trello_collector = { path = "../trello_collector" }
collector = { path = "../collector" }
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.61"
tantivy = "0.13.3"
