[package]
name = "git_collector"
version = "0.1.0"
authors = ["Sahandevs <sahandevs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.13"
bucket = { path = "../bucket" }