[package]
name = "trello_collector"
version = "0.1.0"
authors = ["Sahandevs <sahandevs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
collector = { path = "../collector" }
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.61"
#rayon = "1.5.0"